/* Section 20 — FAQ */
'use client';

import { AlertTriangle } from 'lucide-react';
import { Section, FaqItem } from './_helpers';

export function Section20_FAQ() {
  return (
    <Section icon={<AlertTriangle className="w-4 h-4" />} title="20. FAQ" accent="text-purple-400">
      <div className="flex flex-col gap-2.5">
        <FaqItem q="Do I lose my banked chips if I crash?" a="No! Your banked chips are 100% safe. You only lose the buy-in chips carried in that specific match." />
        <FaqItem q="How does the referral program work?" a="Every player gets a referral code (VIPER-XXXX format) — find it in Profile → Tag & Referral. Share it with a friend; they enter it in the Referral Code field while registering (it can only be entered during registration). Once your friend completes 5 matches, you BOTH automatically receive 2,500 chips. Track your referred friends and their progress in Profile → Referrals." />
        <FaqItem q="How do I get the email verification bonus?" a="Register with email and password, then verify your email from the banner in Profile → Stats. Verification credits +850 chips instantly (150 starter + 850 bonus = 1,000 total). The bonus is one-time per account. Social-login accounts are verified automatically, and guests who upgrade can verify afterwards too." />
        <FaqItem q="Why do I need to select my country?" a="Your country decides which regional server you play on — the nearest one, for the lowest latency. Guests pick it on the login screen; registered players pick it during registration. You can change it later in Profile → Stats → edit, once every 7 days (Faction Region cooldown)." />
        <FaqItem q="Why do I see an ad before joining an online arena?" a="Online arena joins require one short rewarded ad, which unlocks 10 minutes of unlimited entries (each entry still pays its own buy-in). Ads appear ONLY on this join screen — never during gameplay. Time Pass holders never see any ads." />
        <FaqItem q="What is a Time Pass and what are Virtual Tickets?" a="A Time Pass (bought in the mobile app) removes ALL ads for its duration — 5 days to 1 year — and bundles Virtual Tickets upfront. Each Virtual Ticket is one completely free entry (no buy-in, no ad) to the Jade Corridor arena. Time stacks when you buy again. All pass and ticket purchases are final and non-refundable." />
        <FaqItem q="What happens to my chips on January 1?" a="Every wallet resets to zero for the New Year Championship — a fresh, equal start for everyone. Your level, stats, cosmetics, Ad-Free Time Passes and Virtual Tickets are completely untouched. Earn fresh chips through gameplay, claims and reward ads." />
        <FaqItem q="If I buy a Time Pass in December, do I lose the leftover days after January 1?" a="No. Time Pass time is real purchased time — it stacks and carries straight across the January 1 wallet reset. A 1-Year pass bought on December 18 stays ad-free until December 18 of the next year, and its Virtual Tickets are never removed. Only banked chips reset for the fresh championship season." />
        <FaqItem q="What is the graduated commission?" a="If ≤3 real players are in the arena, extraction is FREE (0%). If ≥4 real players, 35% commission applies (you keep 65%)." />
        <FaqItem q="Why did my extraction restart from 0%?" a="Any steering (changing direction) while extracting resets the 3-second progress to 0%. Forward gliding is natural and allowed — just don't turn!" />
        <FaqItem q="What is the green ring near extracting players?" a="When YOU are extracting, a white-to-green progress ring appears near your snake head. It's private — only you can see your own extraction ring." />
        <FaqItem q="Can I Play Again if I don't have enough chips?" a="No. Play Again checks your banked chip balance before letting you rejoin. If you don't have enough chips for the buy-in, you'll see an error and need to earn more chips first." />
        <FaqItem q="Can I extract at any time?" a="Yes! No minimum chip threshold and no zone restriction. Extract from anywhere on the map." />
        <FaqItem q="What happens to bots at score 100?" a="(Online only) They enter self-destruct: slowly navigate toward the wall without boosting, collecting food on the way. Wall death = vanish cleanly." />
        <FaqItem q="Is this gambling?" a="No. Chips are free in-game soft currency with no real-world value. The buy-in is a gameplay risk mechanic, not a wager." />
        <FaqItem q="How does anti-cheat work?" a="Server is authoritative. All chip creation, food eating, collisions, extraction computed server-side. Client only sends steering input." />
        <FaqItem q="Do challenge missions carry over?" a="No. Daily missions reset every day at UTC midnight. Weekly missions reset every Monday at UTC midnight. Complete and claim before the period ends!" />
        <FaqItem q="Can I claim a mission reward twice?" a="No. Each mission can only be claimed once per period. The server prevents double-claiming — even if you refresh or use a different browser." />
        <FaqItem q="Do I earn XP when I die?" a="Yes — XP (score ×5 + kills ×50, scaled by the arena multiplier) is awarded whether you extract or die. What you lose on death are your carried chips: they drop as stars for others. Extract safely to bank chips!" />
        <FaqItem q="How do rewarded ads work?" a="Inside the mobile app, the Chip Store offers Daily Reward Ads: watch a real rewarded video and 50 chips are credited to your wallet automatically after Google verifies the watch server-side. Max 12 ads per day (600 free chips)." />
        <FaqItem q="What are the milestone badges (Rookie, Bronze, Silver, Gold, Platinum, Diamond, Omega)?" a="Milestone badges represent your lifetime achievement level. They are automatically assigned based on your total banked chips: Rookie (0-99K), Bronze (100K+), Silver (500K+), Gold (1M+), Platinum (2.5M+), Diamond (5M+), Omega (10M+). Your badge upgrades instantly when you cross a threshold, and can downgrade if your banked chips drop below the requirement. Each time you reach a new tier, it&apos;s recorded in your Milestone History with the exact timestamp." />
        <FaqItem q="Can I lose my milestone badge?" a="Yes. Your badge is calculated from your current banked chip balance in real-time. If you buy into an arena with a high buy-in and die (losing those chips), your banked balance may drop below your tier threshold, causing a downgrade. Only extracted chips count!" />
        <FaqItem q="How does tie-breaking work on the leaderboard?" a="When two players have the same banked chips, the system checks: (1) Higher level wins. (2) If still tied, the player who joined the game earlier wins (veteran advantage). You&apos;ll see a visible badge on tied rows — &quot;⚔ Lower Lv&quot; if they lost on level, or &quot;🕐 Joined Later&quot; if they lost on join date. This applies on every tab." />
        <FaqItem q="What is the Milestone History section?" a="It&apos;s a collapsible panel above the leaderboard tabs that shows your personal tier achievement timeline. Each milestone you&apos;ve reached displays the badge, chips you had when you achieved it, and the exact date/time (UTC). A progress bar shows how many of the 6 tiers you&apos;ve unlocked, and a &quot;Next milestone&quot; hint tells you what to aim for. If you haven&apos;t achieved any milestones yet, demo data is shown as a preview." />
        <FaqItem q="How does Find Me work?" a="Each leaderboard tab has its own Find Me button. Click it and the system checks if you&apos;re on the current visible list. If yes, it scrolls to your row and highlights it. If not (e.g., you&apos;re viewing a different country or tier), a Rank Summary Card appears showing your Global Rank, National Rank, Regional Rank, banked chips, level, clan tag, and milestone history. On the Summit tab, Find Me shows your National (your country) rank instead of Summit rank." />
        <FaqItem q="How do I reset my password if I forgot it?" a="Go to the Login page → click &quot;Forgot Password?&quot; → enter your registered email + 4-digit Security PIN → set a new password. This works instantly — no email verification needed. Important: you must have set a Security PIN during registration or in Profile → Security Settings. Without a PIN, password recovery is not available." />
        <FaqItem q="How do I change or set my Security PIN?" a="Go to Profile → Agent Profile → Security Settings card. If you already have a PIN, enter your current PIN first, then set a new one. If you don&apos;t have a PIN yet, you can set one without entering a current PIN. Your PIN is required for password recovery — don&apos;t forget it!" />
        <FaqItem q="How does social login (Google, Facebook, Apple) work?" a="Click the provider button on the login page. You&apos;ll be redirected to sign in with your social account. After authorization, a Venom Arena account is automatically created (or linked if your social email matches an existing account). You get 150 starter chips and a VM-XXXXXX tag just like regular registration. No separate password needed." />
        <FaqItem q="Can I link a password to my social login account?" a="Yes! Go to Profile → Agent Profile → Security Settings. You can change your Security PIN there. If you need a full password (for email login), contact support. Your social login always works regardless." />
        <FaqItem q="How does championship registration work?" a="You&apos;re automatically enrolled in the Annual Championship when you play your first online match of the year. Registration is DB-backed — your VM-XXXXXX tag, match history, and standings are stored server-side. Guest accounts must register or link a social account before their championship stats are tracked." />
        <FaqItem q="What happens when the championship year ends?" a="On December 31st at 23:59 UTC, all scoring stops and standings are frozen. On January 1st, prizes are distributed based on final ranks: #1 gets 5M chips + crown, #2–10 get 2.5M each, #11–50 get 1M each, #51–100 get 250K each. The previous year is archived and viewable via the year selector. A new championship year begins immediately with everyone&apos;s scores reset to zero." />
        <FaqItem q="How do clan rankings work in the championship?" a="Clan rankings aggregate the championship scores of all clan members. Every member&apos;s score contributes to the clan total. The clan with the highest combined score across all members ranks #1. The CLAN tab on the championship standings page shows each clan&apos;s total score, member count, and average score per member." />
        <FaqItem q="What is the Hall of Fame?" a="The Hall of Fame is Venom Arena&apos;s permanent record of legendary players. There are two induction paths: (1) Milestone Induction — reach lifetime chip thresholds (1 Lakh to 1 Crore). (2) Championship Induction — finish in the top 100 of an Annual Championship. Once inducted, your record is permanent and can never be removed." />
        <FaqItem q="How do I get into the Hall of Fame?" a="For milestones: simply play and bank chips. When your total banked chips cross a milestone threshold (100K, 500K, 1M, 2.5M, 5M, 10M), you&apos;re automatically inducted if it&apos;s your first time reaching that tier. For championships: finish in the top 100 of any Annual Championship year. Inductions are automatic and DB-backed." />
        <FaqItem q="What are the HOF badges?" a="Milestone badges: 🥉 Bronze Elite (100K+), 🥈 Silver Commander (500K+), 🥇 Gold Apex Vanguard (1M+), 💎 Platinum Sovereign (2.5M+), 🔮 Diamond Warlord (5M+), 👑 Omega Immortal God (10M+). Championship badges: 👑 Crown (#1), 🥈 Silver (#2-10), 🥉 Bronze (#11-50), 🛡️ Contender (#51-100). Your highest badge is displayed on the leaderboard and player inspector." />
        <FaqItem q="Can I be inducted into both milestone and championship HOF?" a="Absolutely! They are separate tracks. A player can hold multiple milestone inductions (one per tier) plus championship inductions (one per year). All appear in your HOF profile on the Hall of Fame tab." />
        <FaqItem q="Are HOF records permanent?" a="Yes. HOF entries are immutable once created. Even if your banked chips drop below a milestone threshold later, your HOF induction for that tier remains. Championship entries are finalized when the year ends and locked forever." />
        <FaqItem q="How do I create a syndicate?" a="Go to the Syndicates tab → click &quot;Form Syndicate&quot; → enter a Name (3+ chars), Tag (3-5 uppercase letters/numbers), Description, and pick an Emblem (6 preset options). You become the Leader automatically. You must not already be in a clan." />
        <FaqItem q="Can I be in multiple syndicates?" a="No. You can only be a member of one syndicate at a time. To join another, you must leave your current syndicate first." />
        <FaqItem q="What happens to my deposited chips if I leave a syndicate?" a="You can now withdraw chips you deposited (up to what you put in) while you're still in the clan. However, if you leave, your unwithdrawn deposits are forfeited — they stay in the Treasury and cannot be recovered. Think carefully before leaving." />
        <FaqItem q="What happens if the Leader leaves?" a="If the Leader leaves, the oldest Co-Leader is automatically promoted to Leader. If there are no Co-Leaders, the oldest member becomes Leader. If you&apos;re the last member, the syndicate is automatically disbanded." />
        <FaqItem q="How do weekly challenges work?" a="Four challenges are generated every Monday UTC: Treasury Target, Recruitment Drive, Syndicate Comms, and Deposit Streak. All scale with your clan level. Deposit Streak counts each deposit transaction (any member, any amount). When a challenge is complete, any Leader or Co-Leader can click Claim to add the reward chips to the Treasury and grant clan XP. Unclaimed challenges reset on the next Monday." />
        <FaqItem q="How does clan XP work?" a="Clan XP is earned two ways: (1) Deposits grant 5% of the deposited amount as XP. (2) Claiming a challenge grants 10% of the reward as XP. The XP needed to level up is Level × 1,000 (e.g. Level 2 needs 2,000 total XP, Level 3 needs 3,000 total XP). Leveling up is logged in the Activity Log." />
        <FaqItem q="What can a Co-Leader do?" a="Co-Leaders can: claim weekly challenges, kick Viper-ranked members, and participate in all clan activities. They cannot: edit clan settings, disband the clan, promote/demote other members, or kick other Co-Leaders. Max 2 Co-Leaders per clan." />
        <FaqItem q="Can the Leader transfer leadership?" a="Yes. The Leader can transfer leadership to any Co-Leader via the crown icon on the member roster. The current Leader becomes a Co-Leader, and the selected Co-Leader becomes the new Leader. This is irreversible for that session." />
        <FaqItem q="What happens when a syndicate is disbanded?" a="All members are removed from the clan, all activity logs and challenge records are deleted, and the Treasury chips are lost. Disbanding is permanent and can only be done by the Leader." />
        <FaqItem q="What is the Agent Profile?" a="The Agent Profile (Profile tab in lobby) is your personal command center with three tabs. The Stats tab shows your identity, level, chips, K/D, cosmetics loadout, shareable profile/milestone cards, security settings, and account management. The History tab shows your match history with filters for All, Extracted, or Collided matches. The Settings tab has help & support, audio, mobile options (orientation, performance, vibration), legal & data, and app info." />
        <FaqItem q="How do I edit my name, country, avatar, or social links?" a="On the Stats tab of Agent Profile, click the edit icon. You can change: (1) Challenger Handle (30-day cooldown), (2) Faction Region / Country (7-day cooldown), (3) Avatar (upload image or pick preset — no cooldown), (4) Social links — Instagram, YouTube, Twitch (no cooldown). Click Save to apply all changes at once. If a cooldown is active, the save is blocked and remaining time is shown." />
        <FaqItem q="What are Profile Cards and Milestone Cards?" a="On the Stats tab, you can generate shareable image cards. The Profile Card shows your name, tag, country flag, level, chips, K/D, cosmetics, and social links. The Milestone Card shows your highest milestone badge and chip progress. Both can be downloaded as images, copied to clipboard, or shared via the Web Share API." />
        <FaqItem q="How do I change my password or Security PIN?" a="Scroll to the Security Settings card on the Stats tab. Registered accounts can change their password (enter current + new). You can also set or change your 4-digit Security PIN — this is required for password recovery. If you already have a PIN, enter the current one first. Guest accounts cannot use Security Settings." />
        <FaqItem q="How do I upgrade from Guest to Registered?" a="Guest accounts see an upgrade banner at the top of the Stats tab. Click it to add an email and password. All progress carries over — chips, stats, cosmetics, streaks, friends, and clan memberships. You keep your VM-XXXXXX tag." />
        <FaqItem q="Can I delete my account?" a="Yes. At the bottom of the Stats tab is a Danger Zone section with a Delete Account button. You must type &quot;DELETE&quot; to confirm, and a second confirmation dialog appears. This permanently removes all chips, stats, cosmetics, friends, match history, and clan memberships. This action is irreversible." />
        <FaqItem q="Can I change my display name?" a="Yes, but with a 30-day cooldown. Your Challenger Handle can only be changed once every 30 days. Go to Profile → Agent Profile (Stats tab) → click the edit icon. Your VM-XXXXXX tag is permanent and can never be changed — it is your true identity on all leaderboards and records." />
        <FaqItem q="Can I change my country/region?" a="Yes, with a 7-day cooldown. Your Faction Region can only be changed once every 7 days. Go to Profile → Agent Profile (Stats tab) → click the edit icon. The change takes effect immediately on leaderboards and championship standings. Your VM-XXXXXX tag remains the same." />
        <FaqItem q="Why is there a cooldown on name and country changes?" a="Without cooldowns, players on the leaderboard could change their name or country to impersonate others, confuse rivals, or exploit regional/national leaderboards. The cooldown limits how often identity can change. Note: leaderboards always show your CURRENT name and country (not historical snapshots), so the cooldown keeps entries stable during ranking periods. Your permanent VM-XXXXXX tag ensures identity continuity across all leaderboards." />
        <FaqItem q="If I change my name on the leaderboard, does my old name disappear?" a="Yes. Leaderboards display your current Challenger Handle in real-time — they do not store historical name snapshots. However, your permanent VM-XXXXXX tag is always shown alongside your name, so players can always identify you regardless of name changes. Hall of Fame entries DO snapshot your name at the time of induction — those never change." />
        <FaqItem q="How do I add a friend?" a="Three ways: (1) Enter their VM-XXXXXX tag in the Add Friend bar at the top of the Social panel. (2) Go to Search Players tab, find them, and click Connect. (3) When killed by a real player, click &quot;Add Friend&quot; on the game-over screen. They must accept your request to become friends." />
        <FaqItem q="What is the difference between Friends and Followers?" a="Friends require mutual acceptance — you send a request, they accept. Followers are one-way — anyone can follow you without your approval, and you can follow anyone without theirs. Following does NOT make someone your friend." />
        <FaqItem q="How does gifting work?" a="On the Friends tab, click &quot;Gift +25c&quot; on any accepted friend&apos;s card. 25 chips are deducted from you and credited to them instantly (atomic transaction). There&apos;s a 30-second cooldown per friend. You can only gift accepted friends — not pending requests or yourself." />
        <FaqItem q="What happens when I block someone?" a="They are removed from your friends list, cannot send you friend requests, and are hidden from your Search Players results. To undo, go to the expandable &quot;Blocked Players&quot; section on the Friends tab and click Unblock. This allows requests again but does NOT re-add them as a friend." />
        <FaqItem q="How do Rivals work?" a="Rivals are cosmetic tracking — no gameplay effect. Add a rival from the game-over kill screen (&quot;Add Rival&quot; button) or the Player Inspector. The Rivals tab shows your W/L record and win rate % against each rival. You can remove rivals or send them a friend request from the Rivals tab." />
        <FaqItem q="How does player search work?" a="The Search Players tab lets you find anyone by name or tag (300ms auto-debounce). You can also filter by country using the dropdown. Results show 20 players per page with a Load More button. Each result displays a relation badge (You / Connected / Sent / Accept / Connect) and key stats. Blocked players never appear in results." />
        <FaqItem q="What is the Highlights tab?" a="The Highlights tab is the community showcase. It displays Match Cards (auto-generated from impressive matches) and Video Clips (player-submitted YouTube/Instagram/Twitch links). The feed also shows a Live Stats Ticker with today's platform activity." />
        <FaqItem q="How do I get a Match Card on the Highlights feed?" a="Match Cards are auto-published when your match meets ANY threshold: Extraction with 5,000+ chips earned, Extraction with 3+ kills, OR Death with 5+ kills. No manual action needed — if your match is impressive enough, it appears automatically and instantly (no review required)." />
        <FaqItem q="How do I submit a video clip?" a="Click the Upload Clip button on the Highlights tab. Choose your platform (YouTube, Instagram, Twitch), paste the video URL, add a title (5-120 chars) and optional description (300 chars max). Your clip enters &quot;Pending&quot; status and must be approved by an admin before it's visible to others. YouTube thumbnails are auto-extracted." />
        <FaqItem q="How is the &quot;Top Play&quot; spotlight chosen?" a="Three-tier priority: (1) Admin-featured clip — if an admin has pinned one. (2) Today's best Match Card — highest chips extracted, then kills as tiebreaker. (3) Highest upvoted approved clip of all time. The spotlight updates on page refresh." />
        <FaqItem q="Can I undo an upvote?" a="No. Upvotes are one-per-player-per-clip and are permanent. This prevents manipulation and keeps the Top Play ranking stable. Choose wisely before upvoting." />
        <FaqItem q="Why is my submitted clip not showing up?" a="Video clips require admin review before becoming visible. Check the Highlights tab with &quot;My Clips&quot; toggled on — if your clip shows &quot;Pending&quot; status, it's still waiting for review (target: 24 hours). If it shows &quot;Rejected&quot;, it didn't meet community guidelines. Match Cards are auto-approved and appear instantly." />
        <FaqItem q="How do I withdraw chips from the clan treasury?" a="Enter the amount in the same deposit input field on the clan Overview tab and click the red &quot;Withdraw&quot; button. You can only withdraw up to what you personally deposited (your deposited amount is tracked individually). The treasury must have enough chips. If you leave the clan, your unwithdrawn deposits are forfeited." />
        <FaqItem q="How does the payout system work?" a="Leader or Co-Leader enters an amount in the treasury input and clicks the green payout icon (Coins button) on a member's row. Those chips are deducted from the treasury and added directly to the member's personal bank. Use this to reward active members or distribute winnings." />
        <FaqItem q="What does the Clan Shop sell?" a="Three items: (1) Member Expansion (15,000c) — adds 5 member slots, repeatable. (2) XP Windfall (8,000c) — instant Level × 500 XP, repeatable. (3) War Shield (5,000c) — 7-day peace mode, no other clan can declare war on you, one-time. Only the Leader can purchase, using treasury chips. The Shop appears on the Overview tab." />
        <FaqItem q="How do Clan Wars work?" a="No separate arenas — members play normal matches. Step by step: (1) Leader declares war on a target clan and enters a wager (min 1,000c). (2) Both clans&apos; treasuries are deducted the wager immediately — held in escrow. (3) Every member of BOTH clans plays their normal matches. After each match, the real-player kills (bot eliminations don&apos;t count) are automatically added to their clan&apos;s war score. (4) Check the Wars tab to see live score bars. (5) First clan to reach 50 total kills wins the entire pot (wager × 2). Only one active war per clan. War Shield (5,000c from shop) blocks declarations against your clan for 7 days." />
        <FaqItem q="Can I create multiple clans?" a="You can only be in one syndicate at a time. If you leave or disband your current clan, you can create a new one. There is no lifetime limit on how many clans you can create across your account." />
        <FaqItem q="What is the Cyber Pass?" a="The Cyber Pass (Season Pass) is a 20-tier progression reward system. You earn Pass XP by playing online matches (50% of your match XP, capped at 1,500/day) and tiers unlock automatically as your Pass XP accumulates — Tier 1 needs 0, Tier 20 needs 55,000 total Pass XP. Every tier contains an exclusive snake skin plus a chip bonus on the free track, and a premium skin with a bigger chip bonus on the elite track (Elite Cyber Pass, 100,000c one-time purchase)." />
        <FaqItem q="How do I earn XP for the Cyber Pass?" a="You earn XP from EVERY online match outcome — extraction or death. Match XP = (score × 5 + kills × 50) × the arena's reward multiplier, and 50% of it becomes Pass XP (capped at 1,500 Pass XP per day). Daily challenge claims also grant +25 XP each. Dying still earns XP — what you lose on death is your carried chips, never your XP." />
        <FaqItem q="Do Cyber Pass rewards carry over between seasons?" a="Currently there is only one season (Genesis). Claimed cosmetics are permanently added to your inventory and will not be removed, even if future seasons are introduced. Elite status is also permanent." />
        <FaqItem q="Can I claim pass rewards retroactively if I already have the Pass XP?" a="Yes! Pass tiers are based on your total Pass XP, and progress never expires mid-season. If your Pass XP already meets a tier&apos;s requirement, it&apos;s already unlocked — just go to the Pass tab and click Claim (or Claim All). The server validates your Pass XP, so every tier up to your current progress is claimable right now." />
        <FaqItem q="Is the Elite Cyber Pass worth it?" a="The Elite track contains 20 premium-exclusive skins (with bigger chip bonuses) that are NEVER sold in the Shop — they are only available through the pass. At 100,000c, it&apos;s a one-time purchase (no subscription). If you play regularly and plan to climb into the higher pass tiers, the elite skins alone are worth far more than the cosmetic shop prices." />
        <FaqItem q="Where do claimed pass cosmetics go?" a="Claimed cosmetics are added to your `unlockedSkins` inventory (server-persisted). To equip them, go to the Shop &amp; Lab tab in Lobby Station. They appear alongside shop-purchased cosmetics and can be equipped as your active snake skin." />
        <FaqItem q="How do player levels work?" a="Every online match grants XP: (score × 5 + kills × 50) × the arena&apos;s reward multiplier — win or lose, extract or die. Each daily/weekly challenge claim adds +25 XP. Level N requires (N − 1) × 200 total XP, so every level costs a steady 200 XP. Your level sets your challenge tier (Novice 1–5, Operative 6–15, Veteran 16–30, Elite 31+) and its reward multiplier (×1.0/×1.5/×2.5/×4.0). It is shown in the header badge and on the Lobby HQ dashboard." />
        <FaqItem q="What is the difference between my Login Streak and Challenge Streak?" a="They are two independent streaks. The LOGIN STREAK (Claims tab, also shown as &apos;Streak&apos; on the dashboard) counts consecutive daily reward claims — it follows the 7-day reward cycle and can be protected with Streak Freezes. The CHALLENGE STREAK (Tactical Challenges header) counts consecutive days where you claimed ALL 3 daily challenges — it multiplies challenge rewards (×1.5 at 3 days, ×2.0 at 7 days, ×3.0 at 14 days) and cannot be protected by freezes. Missing either one resets only that streak, never both." />
      </div>
    </Section>
  );
}
